backend/controllers/SignInController.php
<?php
/**
 * Created by PhpStorm.
 * User: zein
 * Date: 8/2/14
 * Time: 11:20 AM
 */

namespace backend\controllers;

use backend\models\LoginForm;
use backend\models\AccountForm;
use common\models\User;
use common\models\UserProfile;
use frontend\modules\user\models\Signupauto;
use Intervention\Image\ImageManagerStatic;
use trntv\filekit\actions\DeleteAction;
use trntv\filekit\actions\UploadAction;
use Yii;
use yii\filters\VerbFilter;
use yii\helpers\VarDumper;
use yii\web\UploadedFile;
use yii\web\Controller;

class SignInController extends Controller
{

    public $defaultAction = 'login';

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post']
                ]
            ]
        ];
    }

    public function actions()
    {
        return [
            'oauth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'successOAuthCallback']
            ],
            'avatar-upload' => [
                'class' => UploadAction::className(),
                'deleteRoute' => 'avatar-delete',
                'on afterSave' => function ($event) {
                    /* @var $file \League\Flysystem\File */
                    $file = $event->file;
                    $img = ImageManagerStatic::make($file->read())->fit(215, 215);
                    $file->put($img->encode());
                }
            ],
            'avatar-delete' => [
                'class' => DeleteAction::className()
            ]
        ];
    }

    public static function tis620_to_utf8($text) {
        $utf8 = "";
        for ($i = 0; $i < strlen($text); $i++) {
            $a = substr($text, $i, 1);
            $val = ord($a);

            if ($val < 0x80) {
                $utf8 .= $a;
            } elseif ((0xA1 <= $val && $val < 0xDA) || (0xDF <= $val && $val <= 0xFB)) {
                $unicode = 0x0E00+$val-0xA0; $utf8 .= chr(0xE0 | ($unicode >> 12));
                $utf8 .= chr(0x80 | (($unicode >> 6) & 0x3F));
                $utf8 .= chr(0x80 | ($unicode & 0x3F));
            }
        }
        return $utf8;
    }

    public function actionGoback() {
            $profile = Yii::$app->user->identity->userProfile;
            
            $profile->sitecode = Yii::$app->user->identity->userProfile->department;
            if ($profile->save()) {
                $this->redirect(Yii::getAlias('@backendUrl')); //return $this->redirect("/");
            }else{
                VarDumper::dump($model->getErrors(),10,true);
            }        
    }
    
    public function actionLogin()
    {
        $this->layout = 'base';
	
	
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $profile = Yii::$app->user->identity->userProfile;
            
            $profile->sitecode = Yii::$app->user->identity->userProfile->department;
            if (!$profile->save()) {
                VarDumper::dump($model->getErrors(),10,true);
            }
            
            setcookie("CloudUserID", Yii::$app->user->identity->userProfile->user->username, time()+180000, "/", Yii::$app->keyStorage->get('frontend.domain'), false);


            $TCC['username']=Yii::$app->request->post('LoginForm')['username'];
            $TCC['password']=Yii::$app->request->post('LoginForm')['password'];
            $TCC['email']=Yii::$app->user->identity->userProfile->email;
            $TCC['fname']=Yii::$app->user->identity->userProfile->firstname;
            $TCC['lname']=Yii::$app->user->identity->userProfile->lastname;
            $TCC['cid']=Yii::$app->user->identity->userProfile->cid;
            $TCC['mobile']=Yii::$app->user->identity->userProfile->telephone;
            $TCC['office']=Yii::$app->user->identity->userProfile->sitecode;
            $addr = Yii::$app->db->createCommand("Select * from all_hospital_thai where code5=:office",[':office'=>$TCC['office']])->queryOne();
            $TCC['address']=$addr['name'];
            $TCC['tambon']=$addr['provincecode'].$addr['amphurcode'].$addr['tamboncode'];
            $TCC['amphur']=$addr['provincecode'].$addr['amphurcode']."00";
            $TCC['changwat']=$addr['provincecode']."0000";

            setcookie("CloudUser", base64_encode(json_encode($TCC)), time()+180000, "/", Yii::$app->keyStorage->get('frontend.domain'), false);
            //echo VarDumper::dump($TCC,10,true); exit;
            return $this->goBack();
        } else {
            //check from CASCAP Tools Database
            if(Yii::$app->request->post()){
                $loginForm = Yii::$app->request->post('LoginForm');

                //เช็คข้อมูลที่เดิม ว่ามีข้อมูลหรือไม่
                $resx = Yii::$app->db->createCommand("SELECT `id` FROM `user` WHERE username = '".$loginForm['username']."';")->queryOne();
                if($resx['id']) {
                    return $this->render('login', [
                        'model' => $model
                    ]);
                }else{
                    $resx = Yii::$app->db->createCommand("SELECT `user_id` FROM user_profile WHERE cid = '".$loginForm['username']."';")->queryOne();
                    if($resx['user_id']) {
                        return $this->render('login', [
                            'model' => $model
                        ]);
                    }
                }
                $res = Yii::$app->dbcascap->createCommand("SELECT pid, username, passwords, `name`, `surname`, cid, OrganizationName, `Email`, `Phone` FROM puser WHERE username = '".$loginForm['username']."';");
		
                if($res->query()->count()){
                    $res = $res->queryOne();

                    if($loginForm['password'] == $res['passwords']){
                        //VarDumper::dump('pass', 10, true);
                        //Yii::$app->end();
                        $signup = new Signupauto();
                        $signup->username = $res['username'];
                        $signup->password = $res['passwords'];
                        $signup->email = $res['Email'];
                        //
                        $mprofile = new UserProfile();
                        $mprofile->sitecode = $res['OrganizationName'];
                        $mprofile->firstname = $this->tis620_to_utf8($res['name']);
                        $mprofile->lastname = $this->tis620_to_utf8($res['surname']);
                        $mprofile->email = $res['Email'];

                        $resx = Yii::$app->dbcascap->createCommand("select nologin from puser_priv WHERE pid = '".$res['pid']."';");

                        if($resx->query()->count()) {
                            $resx = $resx->queryOne();
                            //ยัง login ไม่ได้
                            if($resx['nologin']==1){
                                $mprofile->status = 0; // ให้เป็นบุคลากรทั่วไป
                            }else if($resx['nologin']==0  || $resx['nologin'] == ""){
                                $mprofile->status = 1; // ให้เป็นบุคลากร
                            }
                        }else {
                            $mprofile->status = 0; // ให้เป็นบุคลากรทั่วไป
                        }

                        $mprofile->status_personal = 3; //ผู้ให้บริการด้านการแพทย์และสาธารณสุข
                        $mprofile->locale = Yii::$app->language;
                        $mprofile->nation = 0;
                        $mprofile->cid = $res['cid'];
                        $mprofile->telephone = $res['Phone'];
                        $mprofile->department = $res['OrganizationName'];

                        //VarDumper::dump($mprofile, 10, true);
                        //Yii::$app->end();
                        $signup->signup($mprofile);

                        $model = new LoginForm();
                        if ($model->load(Yii::$app->request->post()) && $model->login()) {
                            setcookie("CloudUserID", Yii::$app->user->identity->userProfile->user->username, time()+180000, "/", Yii::$app->keyStorage->get('frontend.domain'), false);
                            return $this->goBack();
                        }
                    }
                }
                //Yii::$app->end();
            }
	    //return $this->redirect(\Yii::getAlias('@frontendUrl').'/user/sign-in/login');
	    
            return $this->render('login', [
                'model' => $model
            ]);
        }
    }

    public static function actionViewimg($img)
    {
        return \backend\modules\ovcca\classes\OvccaFunc::getIframeFUrl($img);
    }
    
    public function actionLogout()
    {
        Yii::$app->user->logout();
        setcookie("CloudUserID", Yii::$app->user->identity->userProfile->user->username, time()-1, "/", Yii::$app->keyStorage->get('frontend.domain'), false);
        
	return Yii::$app->getResponse()->redirect(Yii::getAlias('@frontendUrl'));
    }

    public function actionProfile()
    {
        // echo "<pre>";
        // print_r($_POST);
        // exit;
        $model = Yii::$app->user->identity->userProfile;
	// \backend\modules\ezforms\components\EzformQuery::getUserProfile(Yii::$app->user->id);
	
	$secret_file_old = $model->secret_file;
	$citizenid_file_old = $model->citizenid_file;


		
        $sqlHospital = "SELECT `hcode` as code,`name` FROM all_hospital_thai WHERE hcode='".$model->sitecode."' ";
        $dataHospital = Yii::$app->db->createCommand($sqlHospital)->queryOne();
        if ($model->load($_POST)) {
	    

	    
	    
	    $model->citizenid_file = UploadedFile::getInstance($model, 'citizenid_file');
	    $model->secret_file = UploadedFile::getInstance($model, 'secret_file');
	    $data = \common\models\UserProfile::getAdminsite($model->sitecode);
	    

backend/views/sign-in/_modal_user_info.php
<?php
use yii\bootstrap\Html;
?>
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="ModalUser">User Info</h4>
    </div>
    <div class="modal-body">

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 text-center">
                        <img src="<?php echo Yii::$app->user->identity->userProfile->getAvatar() ?: '/img/anonymous.jpg' ?>" alt="" class="center-block img-thumbnail img-responsive">
                        <br>
                    </div><!--/col-->

                    <div class="col-xs-12 col-sm-6 col-md-6">


                        <h3><?php echo Yii::$app->user->identity->userProfile->getFullName(); ?></h3>
                        <p><strong>About: </strong> <?php echo $about['code'].' - '.$about['name']; ?></p>
                        <p><strong>Member since: </strong><?php echo Yii::t('backend', '{0, date, full}', Yii::$app->user->identity->created_at); ?></p>
                        <p><strong>Groups: </strong>
                            <?php
                            foreach($usergroup as $val){
                                echo '<span class="label label-success tags">'.$val['item_name'].'</span> ';
                            }
                            ?>
                        </p>
                    </div><!--/col-->
                </div><!--/row-->

                <div class="row" style="margin-bottom: 5px;">
                    <div class="col-xs-12 col-sm-6">
                        <!--                            <h2><strong> 20,7K </strong></h2>-->
                        <!--                            <p><small>Followers</small></p>-->
                        <?php echo Html::a('<span class="fa fa-user"></span> ตั้งค่าผู้ใช้', ['/sign-in/profile'], ['class'=>'btn btn-success btn-block']) ?>
                    </div><!--/col-->
                    <div class="col-xs-12 col-sm-6">
			<?php //echo Html::a('<span class="glyphicon glyphicon-ban-circle"></span> ยกเลิกการเป็นสมาชิก', ['/site/canceluser'], ['data-confirm' => Yii::t('yii', 'คุณต้องการยกเลิกการเป็นสมาชิก หรือไม่?'), 'class'=>'btn btn-warning btn-block', 'data-method' => 'post']) ?>
                        
                    </div><!--/col-->
		    
                </div>

		<div class="row">
		    <div class="col-xs-12 col-sm-6">
                        <?php echo Html::a('<span class="fa fa-edit"></span> เปลี่ยนรหัสผู้ใช้', ['/sign-in/account'], ['class'=>'btn btn-primary btn-block']) ?>
                    </div><!--/col-->
                    <div class="col-xs-12 col-sm-6">
                        <?php echo Html::a('<span class="fa fa-sign-out"></span> ออกจากระบบ', ['/sign-in/logout'], ['class'=>'btn btn-danger btn-block', 'data-method' => 'post']) ?>
                    </div><!--/col-->
		</div>
            </div>
        </div>

    </div>

</div>

backend/views/sign-in/account.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\UserProfile */
/* @var $form yii\bootstrap\ActiveForm */
$this->title = Yii::t('backend', 'Edit account')
?>

<div class="user-profile-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php echo $form->field($model, 'username')->textInput() ?>
    
    <?php //echo $form->field($model, 'password_old')->passwordInput() ?>

    <?php echo $form->field($model, 'password')->passwordInput() ?>

    <?php echo $form->field($model, 'password_confirm')->passwordInput() ?>

    <div class="form-group">
        <?php echo Html::submitButton(Yii::t('backend', 'Update'), ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/sign-in/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \backend\models\LoginForm */

$this->title = Yii::t('backend', 'Sign In');
$this->params['breadcrumbs'][] = $this->title;
$this->params['body-class'] = 'login-page';

?>
<div class="login-box">
    <div class="login-logo">
        <?php echo Html::encode($this->title) ?>
    </div><!-- /.login-logo -->
    <div class="header"></div>
    <div class="login-box-body">
        <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
        <div class="body">
            <?php if(Yii::$app->keyStorage->get('frontend.domain')=='cascap.in.th'){?>
                <div class="col-md-12"><div class="alert alert-success h4">สมาชิก CASCAP Tools สามารถใช้ Username, Password เดิม</div></div>
            <?php } ?>
            <?php echo $form->field($model, 'username') ?>
            <?php echo $form->field($model, 'password')->passwordInput() ?>
            <?php echo $form->field($model, 'rememberMe')->checkbox(['class'=>'simple']) ?>
	    
	    <div style="color:#999;margin:1em 0">
		<?php echo Yii::t('frontend', '<a href="{link}">Forgot your password, click here.</a>', [
		    'link'=>Yii::getAlias('@frontendUrl'). '/user/sign-in/request-password-reset'
		]) ?>
	    </div>
	    <div class="form-group">
		<?php echo Html::a(Yii::t('frontend', 'Need an account? Sign up.'), Yii::getAlias('@frontendUrl'). '/user/sign-in/signup') ?>
	    </div>
        </div>
        <div class="footer">
            <?php echo Html::submitButton(Yii::t('backend', 'Sign me in'), [
                'class' => 'btn btn-primary btn-flat btn-block',
                'name' => 'login-button'
            ]) ?>
        </div>
        <?php ActiveForm::end(); ?>
        <br>
        <center><a href="<?php echo Yii::getAlias('@frontendUrl'); ?>">กลับหน้าหลัก</a>
    </div>

</div>